FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    git \
    cmake \
    build-essential \
    g++ \
    pkg-config \
    casacore-data casacore-dev \
    libblas-dev liblapack-dev \
    python3 \
    libpython3-dev \
    libboost-date-time-dev libboost-test-dev \
    libboost-program-options-dev libboost-system-dev libboost-filesystem-dev \
    libcfitsio-dev \
    libfftw3-dev \
    libgsl-dev \
    libhdf5-dev \
    libopenmpi-dev \
    pkg-config \
    python3-dev python3-numpy \
    python3-pytest \
    python3-sphinx \
    wget

# Install EveryBeam
RUN mkdir /external && \
    cd /external && \
    git clone --depth 1 https://git.astron.nl/RD/EveryBeam.git && \
    mkdir /external/EveryBeam/build && cd /external/EveryBeam/build && \
    cmake ../ && \
    make install -j`nproc`

# Install IDG
RUN cd /external && \
    git clone --depth 1 https://git.astron.nl/RD/idg.git && \
    mkdir /external/idg/build && cd /external/idg/build && \
    cmake ../ && \
    make install -j`nproc`

# Install WSClean
RUN git clone --depth 1 --branch v3.0 https://gitlab.com/aroffringa/wsclean
WORKDIR /wsclean
RUN \
    mkdir /build && \
    cd /build && \
    cmake ../wsclean && \
    make -j`nproc` && \
    make install && \
    wsclean --version

