FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
    apt-get -qq install -y \
    git \
    cmake \
    build-essential \
    g++ \
    pkg-config \
    casacore-data casacore-dev \
    libblas-dev liblapack-dev \
    python3 \
    libpython3-dev \
    libboost-date-time-dev libboost-test-dev \
    libboost-program-options-dev libboost-system-dev libboost-filesystem-dev \
    libcfitsio-dev \
    libfftw3-dev \
    libgsl-dev \
    libhdf5-dev \
    libopenmpi-dev \
    pkg-config \
    python3-dev python3-numpy \
    python3-pytest \
    python3-sphinx \
    wget \
    gpg \
    python3-setuptools  \
    ca-certificates


# Install latest CMake - required for ubuntu 20.04
# Following https://apt.kitware.com/
RUN test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN apt-get -qq update
RUN test -f /usr/share/doc/kitware-archive-keyring/copyright || rm /usr/share/keyrings/kitware-archive-keyring.gpg
RUN apt-get -qq install -y kitware-archive-keyring
RUN apt-get -qq install -y cmake

# Install EveryBeam
# We're using an older version of WSClean that requires EveryBeam v0.4.0
RUN mkdir /external && \
    cd /external && \
    git clone --depth 1 --branch v0.4.0 https://git.astron.nl/RD/EveryBeam.git && \
    mkdir /external/EveryBeam/build && cd /external/EveryBeam/build && \
    cmake ../ && \
    make install -j`nproc`

# Install IDG
RUN cd /external && \
    git clone --depth 1 https://git.astron.nl/RD/idg.git && \
    mkdir /external/idg/build && cd /external/idg/build && \
    cmake ../ && \
    make install -j`nproc`

# Install WSClean
RUN git clone --depth 1 --recurse-submodules -j8 https://github.com/tjgalvin/wsclean
WORKDIR /wsclean
RUN \
    mkdir /build && \
    cd /build && \
    cmake ../wsclean -DPORTABLE=True && \
    make -j`nproc` && \
    make install && \
    wsclean --version

