name: Docker Build and Push

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.5', '3.4', '3.3', '3.2', '3.1', '3.0.1', '3.0', '2.10.1', '2.10'] # Add more versions here
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            alecthomson/wsclean
            ghcr.io/alecthomson/wsclean-docker
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=schedule,pattern=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            alecthomson/wsclean:${{ matrix.version }}
            ghcr.io/alecthomson/wsclean-docker:${{ matrix.version }}
          labels: |
            version=${{ matrix.version }}
          file: ./Dockerfile-${{ matrix.version }} # Use the version for Dockerfile path
